FROM bitnami/spark:latest

WORKDIR /opt/spark/app
COPY spark_stream.py .

CMD ["spark-submit", "--master", "spark://spark-master:7077", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.1", "spark_stream.py"]
